export const CRUCESIGNATI = {
  scores: {
    str: "CRUCESIGNATI.scores.str.long",
    int: "CRUCESIGNATI.scores.int.long",
    dex: "CRUCESIGNATI.scores.dex.long",
    wis: "CRUCESIGNATI.scores.wis.long",
    con: "CRUCESIGNATI.scores.con.long",
    cha: "CRUCESIGNATI.scores.cha.long",
  },
  class: {
    warrior: "CRUCESIGNATI.class.warrior",
    cleric: "CRUCESIGNATI.class.cleric",
    druid: "CRUCESIGNATI.class.druid",
    mage: "CRUCESIGNATI.class.mage",
    paladine: "CRUCESIGNATI.class.paladine",
    ranger: "CRUCESIGNATI.class.ranger",
    thief: "CRUCESIGNATI.class.thief"
  },
  roll_type: {
    result: "=",
    above: "≥",
    below: "≤"
  },
  saves_short: {
    death: "CRUCESIGNATI.saves.death.short",
    wand: "CRUCESIGNATI.saves.wand.short",
    paralysis: "CRUCESIGNATI.saves.paralysis.short",
    breath: "CRUCESIGNATI.saves.breath.short",
    spell: "CRUCESIGNATI.saves.spell.short",
  },
  saves_long: {
    death: "CRUCESIGNATI.saves.death.long",
    wand: "CRUCESIGNATI.saves.wand.long",
    paralysis: "CRUCESIGNATI.saves.paralysis.long",
    breath: "CRUCESIGNATI.saves.breath.long",
    spell: "CRUCESIGNATI.saves.spell.long",
  },
  armor : {
    unarmored: "CRUCESIGNATI.armor.unarmored",
    light: "CRUCESIGNATI.armor.light",
    heavy: "CRUCESIGNATI.armor.heavy",
    shield: "CRUCESIGNATI.armor.shield",
  },
  colors: {
    green: "CRUCESIGNATI.colors.green",
    red: "CRUCESIGNATI.colors.red",
    yellow: "CRUCESIGNATI.colors.yellow",
    purple: "CRUCESIGNATI.colors.purple",
    blue: "CRUCESIGNATI.colors.blue",
    orange: "CRUCESIGNATI.colors.orange",
    white: "CRUCESIGNATI.colors.white"
  },
  languages: [
    "Algandarve",
    "Angate",
    "Beaulangue",
    "Cabbandari",
    "Classico (scritto)",
    "Dakkandi",
    "Elleslandic",
    "Elfico (orale)",
    "Elfico (scritto)",
    "Emphidoriano (orale)",
    "Empidoriano (scritto)",
    "Etya'b'yely",
    "Geroglifici Qemor",
    "Jezant (scritto)",
    "Majestic (scritto)",
    "Mercaniano moderno",
    "Nascerine",
    "Nanico",
    "Ophalariano",
    "Klav",
    "Kell (scritto)",
    "Kurlish",
    "Lugwyd (druidico)",
    "Pittogrammi Khitai",
    "Raukil",
    "Runico (scritto)",
    "Rune Nikkar (scritto)",
    "Unno",
    "Visic"
  ],
  tags: {
    melee: "CRUCESIGNATI.items.Melee",
    missile: "CRUCESIGNATI.items.Missile",
    slow: "CRUCESIGNATI.items.Slow",
    twohanded: "CRUCESIGNATI.items.TwoHanded",
    blunt: "CRUCESIGNATI.items.Blunt",
    brace: "CRUCESIGNATI.items.Brace",
    splash: "CRUCESIGNATI.items.Splash",
    reload: "CRUCESIGNATI.items.Reload",
    charge: "CRUCESIGNATI.items.Charge",
  },
  tag_images: {
    melee: "/systems/crucesignati/assets/melee.png",
    missile: "/systems/crucesignati/assets/missile.png",
    slow: "/systems/crucesignati/assets/slow.png",
    twohanded: "/systems/crucesignati/assets/twohanded.png",
    blunt: "/systems/crucesignati/assets/blunt.png",
    brace: "/systems/crucesignati/assets/brace.png",
    splash: "/systems/crucesignati/assets/splash.png",
    reload: "/systems/crucesignati/assets/reload.png",
    charge: "/systems/crucesignati/assets/charge.png",
  },
  monster_saves: {
    0: {
      g: 0,
      d: 14,
      w: 15,
      p: 16,
      b: 17,
      s: 18
    },
    1: {
      g: 0,
      d: 12,
      w: 13,
      p: 14,
      b: 15,
      s: 16
    },
    4: {
      g: 0,
      d: 10,
      w: 11,
      p: 12,
      b: 13,
      s: 14
    },
    7: {
      g: 0,
      d: 8,
      w: 9,
      p: 10,
      b: 10,
      s: 12
    },
    10: {
      g: 0,
      d: 6,
      w: 7,
      p: 8,
      b: 8,
      s: 10
    },
    13: {
      g: 0,
      d: 4,
      w: 5,
      p: 6,
      b: 5,
      s: 8
    },
    16: {
      g: 0,
      d: 2,
      w: 3,
      p: 4,
      b: 3,
      s: 6
    },
    19: {
      g: 0,
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 4
    },
    22: {
      g: 0,
      d: 2,
      w: 2,
      p: 2,
      b: 2,
      s: 2
    },
  },
  monster_thac0: {
    0: 20,
    1: 19,
    2: 18,
    3: 17,
    4: 16,
    5: 15,
    6: 14,
    7: 13,
    9: 12,
    10: 11,
    12: 10,
    14: 9,
    16: 8,
    18: 7,
    20: 6,
    22: 5
  }
};